replicaCount: 1

image: 
  repository: docker.io/avardhineni7/javalogin:1.0

service:
  type: nodePort
  port: 8080
  nodePort: 31000
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi