#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javalogin-deploy
  labels:
    app: javalogin-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: javalogin-app
  template:
    metadata:
      labels:
        app: javalogin-app
    spec:
      containers:
      - name: javalogin-container
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory}}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
