#Create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks: 
  - name: Pull .war artifact from Artifactory
    become: true
    become_user: root
    get_url:
      url: https://simplifieddevops.jfrog.io/artifactory/javappweb-local/com/iwayq/iwayQApp/5.0/iwayQApp-5.0.war
      dest: .
      url_username: "avardhineni7@gmail.com"
      url_password: "*****"

  - name: Rename .war Artifact
    command: mv iwayQApp-5.0.war javalogin.war
  
  - name: Build image and with build args
    docker_image:
      name: javalogin
      build:
        path: .
        pull: no
        args:
          listen_port: 8080
      source: build

  - name: Log into DockerHub
    docker_login:
     username: avardhineni7
     password: Password777

    
  - name: Push to docker hub
    docker_image:
      name: javalogin
      repository: docker.io/avardhineni7/javalogin:1.0
      push: yes
      source: local
